### ISSUE TITLE
Missing dot icon for unsaved files

### ISSUE THREAD

**Issue by lidessen** [melishev/feather-vscode#1]
Hi, I really like your theme, but  I found that the dot icon for unsaved files disappeared, can you fix it, thank you!!
<img width="183" alt="image" src="https://user-images.githubusercontent.com/8148113/162354303-eed362bf-b732-4545-be11-bc56bb097b57.png">
<img width="249" alt="image" src="https://user-images.githubusercontent.com/8148113/162354336-3a95a308-4c3c-4b8b-95d6-5ae4acd945a9.png">

if I switch to another theme:
<img width="192" alt="image" src="https://user-images.githubusercontent.com/8148113/162354455-d4df7c24-1b1b-44e9-8770-c3057e847e7b.png">

**Comment by stagefright5** [comment]
This is the only thing stopping me from switching to this theme. A fix would be great!

Thanks

**Comment by melishev** [comment]
@aoiste @stagefright5 

Sorry for the delay, I fixed this bug.
He also bothered me, but not so much)
